AddonId: 8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2
Packages:
  - Version: 1.8
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-10-31
    PackageUrl: https://github.com/XenorPLxx/Helium-Enhanced-Grid-Mod/releases/download/1.8/8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2_1_8.pthm
    Changelog:
      - "Ported changes in the original Helium"
      - "General: Animate PlayButton and ContextButton background color transitions"
      - "Details View: Animate info button and edit button opacity transitions"
      - "Grid View: Animate edit button opacity transitions"
      - "Grid View: Modified opacity changes for game item controls"
      - "Grid View: Add highlight shine animation to covers on hover"
      - "Minor fixes and improvements"
      - "Details View: Add ThemeModifier variable to show or hide information panel when Playnite starts"
      - "Details View: Add ThemeModifier variables to configure horizontal and Vertical alignment of the background image"
      - "Details View: Add ThemeModifier variable to configure if Extra Metadata Loader logos can be used in the view"
      - "Details View: Fix Context action button not changing color when game is installing or uninstalling"
      - "Details View: Add support to show grid with game HowLongToBeat data and ThemeModifier option to enable or disable"
      - "Grid View: Add ThemeModifier variable to configure if Extra Metadata Loader logos can be used in the view"
      - "Grid View: Fix Context action button not changing color when game is installing or uninstalling"
      - "Grid View: Add support to show grid with game HowLongToBeat data and ThemeModifier option to enable or disable"
      - "Minor fixes and improvements"
  - Version: 1.6
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-10-19
    PackageUrl: https://github.com/XenorPLxx/Helium-Enhanced-Grid-Mod/releases/download/1.6/8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2_1_6.pthm
    Changelog:
      - "Forked from Helium by darklinkpower"
      - "Modified Grid view to better utilize displays with higher horizontal pixel count"
